# @name get-prompts
GET http://localhost:3333/prompts

### 

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# @name create-transcription
POST http://localhost:3333/videos/582ca610-82c9-45b1-a8f6-2055d6b00512/transcription
Content-Type: application/json

{
  "prompt": "rocketseat, one, tecnologia"
}

### 

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "763d6a21-ae8d-40c5-a43e-a8dc32cb164e",
  "temperature": 0.5,
  "prompt": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''",
  "openAIKey": "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"
}