# @name get-prompts
GET http://localhost:3333/prompts

### 

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# @name create-transcription
POST http://localhost:3333/videos/17443935-d946-4a5f-a168-77a5fb394b07/transcription
Content-Type: application/json

{
  "openAIKey": "",
  "prompt": "IES, MEC"
}

### 

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "17443935-d946-4a5f-a168-77a5fb394b07",
  "temperature": 0.5,
  "prompt": "Gere uma lista dos principais assuntos abordados em formato de tópicos da transcrição do vídeo informada a seguir: '''{transcription}'''",
  "openAIKey": ""
}